spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/cvehub?useUnicode=true&characterEncoding=utf-8
    username: 
    password: 
    driver-class-name: com.mysql.cj.jdbc.Driver
  main:
    allow-bean-definition-overriding: true
  mail:
    host: smtp.qq.com
    username: 1965190613@qq.com
    password: 

logging:
  level:
    root: INFO
    org:
      springframework:
        security: DEBUG
        web: ERROR
      hibernate: DEBUG
      apache:
        commons:
          dbcp2: DEBUG
  file:
    path: log
server:
  port: 8888
##jwt配置
audience:
  # 代表这个JWT的接收对象,存入audience
  clientId: 098f6bcd4621d373cade4e832627b4f6
  # 密钥, 经过Base64加密, 可自行替换
  base64Secret: MDk4ZjZiY2Q0NjIxZDM3M2NhZGU0ZTgzMjYyN2I0ZjY=
  # JWT的签发主体，存入issuer
  name: restapiuser
  # 过期时间，时间戳
  expiresSecond: 172800
mybatis:
  mapper-locations: classpath:mapping/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

docker:
  host: 127.0.0.1
  port: 2375
