spring:
  datasource:
    url: jdbc:mysql://www.sunhanwu.top:3306/cvehub?useUnicode=true&characterEncoding=utf-8
    username: root
    password: Ydm186919
    driver-class-name: com.mysql.cj.jdbc.Driver
server:
  port: 8080